use pll_core::*;

pub struct BootstrapGen;

impl BootstrapGen {
    pub fn generate(&self, program: &Program) -> String {
        let mut out = String::new();
        out.push_str("// Generated by PLL bootstrap\n");
        out.push_str("pub fn run() {\n");
        for stmt in &program.statements {
            match &stmt.value {
                Stmt::VarDecl(v) => {
                    if let Some(init) = &v.init { out.push_str(&format!("    let {} = {};\n", v.name, self.expr_to_rust(init))); }
                }
                Stmt::Render(e) => { out.push_str(&format!("    println!(\"{}\", {});\n", "{}", self.expr_to_rust(e))); }
                Stmt::FnDecl(f) => {
                    let params: Vec<String> = f.params.iter().map(|p| format!("{}: f64", p.name)).collect();
                    out.push_str(&format!("    fn {}({}) -> f64 {{\n", f.name, params.join(", ")));
                    for s in &f.body { self.stmt_to_rust(s, &mut out, 2); }
                    out.push_str("    }\n");
                }
                _ => {}
            }
        }
        out.push_str("}\n");
        out
    }

    fn stmt_to_rust(&self, stmt: &Spanned<Stmt>, out: &mut String, indent: usize) {
        let ind = "    ".repeat(indent);
        match &stmt.value {
            Stmt::Return(e) => out.push_str(&format!("{}return {};\n", ind, self.expr_to_rust(e))),
            Stmt::VarDecl(v) => {
                if let Some(init) = &v.init { out.push_str(&format!("{}let {} = {};\n", ind, v.name, self.expr_to_rust(init))); }
            }
            Stmt::Render(e) => out.push_str(&format!("{}println!(\"{}\", {});\n", ind, "{}", self.expr_to_rust(e))),
            Stmt::If(i) => {
                out.push_str(&format!("{}if {} {{\n", ind, self.expr_to_rust(&i.condition)));
                for s in &i.then_body { self.stmt_to_rust(s, out, indent + 1); }
                if let Some(el) = &i.else_body { out.push_str(&format!("{}}} else {{\n", ind)); for s in el { self.stmt_to_rust(s, out, indent + 1); } }
                out.push_str(&format!("{}}}\n", ind));
            }
            _ => {}
        }
    }

    fn expr_to_rust(&self, expr: &Spanned<Expr>) -> String {
        match &expr.value {
            Expr::Literal(lit) => match lit {
                Literal::Num(n) => n.to_string(), Literal::Str(s) => format!("\"{}\"", s),
                Literal::Bool(b) => b.to_string(), Literal::Nil => "0.0".to_string(),
            },
            Expr::Ident(name) => name.clone(),
            Expr::Binary(op, left, right) => {
                let op_str = match op { BinaryOp::Add => "+", BinaryOp::Sub => "-", BinaryOp::Mul => "*", BinaryOp::Div => "/", _ => "+" };
                format!("({} {} {})", self.expr_to_rust(left), op_str, self.expr_to_rust(right))
            }
            Expr::Call(name, args) => {
                let a: Vec<String> = args.iter().map(|a| self.expr_to_rust(a)).collect();
                format!("{}({})", name, a.join(", "))
            }
            _ => "0.0".to_string(),
        }
    }
}
