"""
GCA (Generational Context Architecture) Orchestrator

Implements the agent lifecycle:
  Birth -> Work -> Document -> Death -> Rebirth

Agents communicate via PLL-formatted messages stored in the vault.
The orchestrator manages the cycle; agents run in the PLL WASM VM.
"""
from datetime import datetime, timezone
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from models import Project, AgentSession, GCAVault

PLL_MESSAGE_TEMPLATE = """# PLL Inter-Agent Message
# Generated by GCA Orchestrator
v sender != "{sender}"
v receiver != "{receiver}"
v msg_type != "{message_type}"
v generation != {generation}
v payload != "{payload}"
"""

class GCAOrchestrator:
    def __init__(self, db: AsyncSession):
        self.db = db

    async def init_cycle(self, project_id: int, objective: str) -> tuple[AgentSession, AgentSession]:
        """Initialize a GCA cycle: create Primary and Shadow agents."""
        project = await self.db.get(Project, project_id)
        if not project:
            raise ValueError("Project not found")

        primary = AgentSession(
            project_id=project_id,
            generation=0,
            agent_type="primary",
            status="born",
            objective=objective,
            current_state="Initializing...",
        )
        # Shadow monitors progress; starts in born status
        shadow = AgentSession(
            project_id=project_id,
            generation=0,
            agent_type="shadow",
            status="born",
            objective=objective,
            current_state="Awaiting promotion...",
        )
        self.db.add_all([primary, shadow])
        await self.db.commit()
        await self.db.refresh(primary)
        await self.db.refresh(shadow)

        # Write initial vault entry
        await self._write_vault(
            project_id, primary.id, "objective.md",
            f"# Objective\n\n{objective}\n\n---\n\n**Generation:** 0\n**Primary:** Session {primary.id}\n**Shadow:** Session {shadow.id}\n"
        )
        return primary, shadow

    async def checkpoint(self, project_id: int, session_id: int, key: str,
                         content: str, current_state: str) -> GCAVault:
        """Save agent state to the vault (the 'External Brain')."""
        session = await self.db.get(AgentSession, session_id)
        if not session:
            raise ValueError("Agent session not found")

        session.status = "documenting"
        session.current_state = current_state
        session.updated_at = datetime.now(timezone.utc)

        vault_entry = await self._write_vault(project_id, session_id, key, content)
        await self.db.commit()
        return vault_entry

    async def handoff(self, project_id: int) -> tuple[AgentSession, AgentSession, AgentSession]:
        """
        Perform agent handoff:
        1. Mark current Primary as 'dead'
        2. Promote Shadow to Primary
        3. Create new Shadow for next generation
        """
        sessions = await self._get_active_sessions(project_id)
        primary = next((s for s in sessions if s.agent_type == "primary" and s.status != "dead"), None)
        shadow = next((s for s in sessions if s.agent_type == "shadow" and s.status != "dead"), None)

        if not primary or not shadow:
            raise ValueError("Need both Primary and Shadow agents for handoff")

        # Capture final state from primary
        final_state = primary.current_state
        next_generation = primary.generation + 1

        # Mark primary as dead
        primary.status = "dead"
        primary.current_state = f"Completed generation {primary.generation}. Handoff to generation {next_generation}."
        primary.updated_at = datetime.now(timezone.utc)

        # Write final vault entry from primary
        await self._write_vault(
            project_id, primary.id, f"generation_{primary.generation}_final.md",
            f"# Generation {primary.generation} Final State\n\n{final_state}\n\n---\n*Handoff to generation {next_generation}*"
        )

        # Promote shadow to primary
        shadow.agent_type = "primary"
        shadow.status = "born"
        shadow.generation = next_generation
        shadow.current_state = final_state
        shadow.updated_at = datetime.now(timezone.utc)

        # Create new shadow
        new_shadow = AgentSession(
            project_id=project_id,
            generation=next_generation,
            agent_type="shadow",
            status="born",
            objective=primary.objective,
            current_state="Awaiting promotion...",
        )
        self.db.add(new_shadow)
        await self.db.commit()
        await self.db.refresh(shadow)
        await self.db.refresh(new_shadow)

        # Write vault entry for the handoff
        await self._write_vault(
            project_id, shadow.id, f"generation_{next_generation}_start.md",
            f"# Generation {next_generation} Start\n\n**Promoted from Shadow.**\n**Previous generation final state:**\n\n{final_state}"
        )

        return primary, shadow, new_shadow

    async def wrap_message(self, sender: str, receiver: str, message_type: str,
                            generation: int, payload: str) -> str:
        """Wrap a message in PLL format for inter-agent communication."""
        return PLL_MESSAGE_TEMPLATE.format(
            sender=sender,
            receiver=receiver,
            message_type=message_type,
            generation=generation,
            payload=payload.replace('"', '\\"'),
        )

    async def get_vault(self, project_id: int) -> list[GCAVault]:
        """Read all vault entries for a project."""
        result = await self.db.execute(
            select(GCAVault)
            .where(GCAVault.project_id == project_id)
            .order_by(GCAVault.created_at.asc())
        )
        return result.scalars().all()

    async def get_status(self, project_id: int) -> dict:
        """Get current GCA status for a project."""
        project = await self.db.get(Project, project_id)
        if not project:
            raise ValueError("Project not found")

        sessions = await self._get_active_sessions(project_id)
        primary = next((s for s in sessions if s.agent_type == "primary" and s.status != "dead"), None)
        shadow = next((s for s in sessions if s.agent_type == "shadow" and s.status != "dead"), None)

        result = await self.db.execute(
            select(GCAVault).where(GCAVault.project_id == project_id)
        )
        vault_count = len(result.scalars().all())

        result = await self.db.execute(
            select(AgentSession).where(AgentSession.project_id == project_id)
        )
        total_generations = max((s.generation for s in result.scalars().all()), default=0)

        return {
            "project_id": project_id,
            "total_generations": total_generations,
            "current_primary": primary,
            "current_shadow": shadow,
            "vault_entries_count": vault_count,
        }

    async def _get_active_sessions(self, project_id: int) -> list[AgentSession]:
        result = await self.db.execute(
            select(AgentSession).where(AgentSession.project_id == project_id)
        )
        return list(result.scalars().all())

    async def _write_vault(self, project_id: int, session_id: int | None,
                           key: str, content: str) -> GCAVault:
        entry = GCAVault(
            project_id=project_id,
            session_id=session_id,
            key=key,
            content=content,
        )
        self.db.add(entry)
        await self.db.flush()
        await self.db.refresh(entry)
        return entry
